### ISSUE TITLE
Autoinstall fastell4py with pip

### ISSUE THREAD

**Issue by jiwoncpark** [jiwoncpark/baobab#19]
Currently, it silently skips the `fastell4py` install.

**Comment by sibirrer** [comment]
there is currently no work-around as fastell4py requires a fortran compiler to be installed properly and I have not found a way how to make this happen through a pip install. It's on my to-do list but I haven't found a solution yet.

**Comment by jiwoncpark** [comment]
@sibirrer I see, thank you! I'll put it on the backlog and update the docs for now.
