### ISSUE TITLE
nans outputted in some images

### ISSUE THREAD

**Issue by swagnercarena** [jiwoncpark/baobab#28]
When running the attached config file (converted to txt to be able to attach)
[train_diagonal.txt](https://github.com/jiwoncpark/baobab/files/3818306/train_diagonal.txt), some of the images that were generated have nans. I attached X_0001650.npy
 as an example. During the image generation the following error is outputted:

```
/anaconda3/lib/python3.6/site-packages/lenstronomy/SimulationAPI/observation_api.py:198: RuntimeWarning: invalid value encountered in sqrt
  noise = np.sqrt(variance) / self.exposure_time
```

![X_0001650](https://user-images.githubusercontent.com/8857025/68368172-48177480-00ec-11ea-8cb5-733e2d96fe8d.png)

**Comment by swagnercarena** [comment]
This seems to be happening in about 0.1% of my images, but I can't find any properties of the lens that it's associated to.

**Comment by drphilmarshall** [comment]
Uh oh. While this does look like a baobab problem, it's also the case that
real images often have features like this (from hot pixels in the detector,
or masked regions from eth processing, etc). The correct way to deal with
them is to use a "weight map" (typically inverse variance) that has zeros
in the problem pixels, set the problem pixels to some MAGIC number, and
then incorporate the weight map into the inference. I'm not saying that
`ovejero` or `h0rton` needs this capability now, but rather that eventually
we will need it to be able to cope with masked regions. And preferably
understand the concept of pixel weight / uncertainty. In the meantime, we
should a) fix baobab and (in parallel) b) reject any baobab images that
have Nans in them.

**Comment by jiwoncpark** [comment]
It's not related to the lens properties but the image properties (noise). It's coming from lenstronomy, specifically [this line](https://github.com/sibirrer/lenstronomy/blob/8a4ec79c6a6797120d43b3fa13b6115d233ff81d/lenstronomy/SimulationAPI/observation_api.py#L187), and I'm guessing this happens for areas with negative flux or if you specified zero exposure time. I've only seen this happen in the low-flux areas (e.g. corners) of images, and dealt with them simply by zero-ing the NaNs. @sibirrer Should this be handled inside lenstronomy? Alternatively, a simple fix in baobab would be to include zero masking in `generate.py`.

**Comment by sibirrer** [comment]
this happens when either lenstronomy produces images with slightly negative pixel values (can be basically zeros with some numerical noise) or if baobab first adds noise and then (on the negative pixels) tries to compute the variance. I will push in lenstronomy a version that solves the problem of taking the sort() of a possible negative pixel value to estimate the noise

**Comment by jiwoncpark** [comment]
@sibirrer Thank you! In `generate.py`, I currently have

 ```
# Generate image for export
img = image_model.image(kwargs_lens_mass, kwargs_src_light, kwargs_lens_light, kwargs_ps)
# Add noise
noise = data_api.noise_for_model(img, background_noise=True, poisson_noise=True, seed=None)
img += noise
```
Since `img` is the model image, it seems like numerical noise making some effectively zero pixels slightly negative? Maybe flooring `img` at 0 will be enough.

**Comment by sibirrer** [comment]
@swagnercarena @jiwoncpark I pushed an update to the master branch of lenstronomy to circumvent this issue of numerical negative numbers. @jiwoncpark you can also 'double save gard' it in baobab before calling the lenstronomy function noise_for_model()

**Comment by jiwoncpark** [comment]
Safeguarding in baobab is there too now. Closing!
