### ISSUE TITLE
testing with lenstronomy

### ISSUE THREAD

**Issue by sibirrer** [jiwoncpark/baobab#34]
https://github.com/jiwoncpark/baobab/blob/a1118b886c56b6eb7fde644db50e2a9602cf7050/baobab/data_augmentation/noise_lenstronomy.py#L51

you can test the definition with the ones used in lenstronomy with single band.background_noise**2 == noise_sigma2['sky'] + noise_sigma2['read_out']
It should be fine but testing never hurts

**Comment by jiwoncpark** [comment]
Added inside `test_noise_numpy` and closing!
