### ISSUE TITLE
noise_tf fails with placeholder shapes / doesn't have a good interface with baobab config files.

### ISSUE THREAD

**Issue by swagnercarena** [jiwoncpark/baobab#37]
Two small issues with noise_tf

1) https://github.com/jiwoncpark/baobab/blob/f1e8ed6f971012dd8b2f83bd951bfa8fff58b05b/baobab/data_augmentation/noise_tf.py#L170

This line will cause a tensorflow error if the image tensor that is passed in has placeholder dimensions. This makes the code incompatible with tf_datasets. A simple change to:

<pre><code>return tf.random.normal(tf.shape(img))*self.get_noise_sigma2(img)**0.5
</code></pre>
 
should resolve this issue.

2)
There is currently no way to map from a baobab config to the inputs required for NoiseModelTF. A function that converts the portions of the baobab config relevant to NoiseModelTF in a dictionary should resolve this issue.

<pre><code>def get_noise_kwargs(baobab_cfg):
	"""
	Return the noise kwargs defined in the babobab config

	Parameters
	----------
		baobab_cfg (BaobabConfig): A BaobabConfig object containing the desired
			noise parameters.

	Returns
	-------
		(dict): A dict containing the noise kwargs to be passed to the noise
			model.
	"""
	# Go through the baobab config and pull out the noise kwargs one by one.
	noise_kwargs = {}
	noise_kwargs.update(baobab_cfg.instrument)
	noise_kwargs.update(baobab_cfg.bandpass)
	noise_kwargs.update(baobab_cfg.observation)
	return noise_kwargs
</code></pre>

**Comment by jiwoncpark** [comment]
Fixed in master, thanks!
