### ISSUE TITLE
Import lines in init are causing problems when tensorflow or torch isn't installed

### ISSUE THREAD

**Issue by swagnercarena** [jiwoncpark/baobab#40]
The code here is written such that the user only needs to have the relevant package (i.e. tensorflow or torch) for the data augmentation they're using. However, the init file imports all the packages, causing the code to crash if both tensorflow and torch are not installed.

https://github.com/jiwoncpark/baobab/blob/636bd2021e9b6d779cf33483e1a6bd47d67d114d/baobab/data_augmentation/__init__.py#L3

**Comment by jiwoncpark** [comment]
Right, it was causing tests to crash but I forgot to comment it out! Done in master and closing.
