### ISSUE TITLE
generate.py now crashes if agn light is not used

### ISSUE THREAD

**Issue by swagnercarena** [jiwoncpark/baobab#53]
generate.py no longer runs after the magnification fixes for configs without agn light. The code returns the following error:

`  File "/Users/sebwagner/Documents/Grad_School/Research/Phil/baobab/baobab/sim_utils/image_utils.py", line 128, in generate_image
    unlensed_total_flux = get_unlensed_total_flux_numerical(self.kwargs_src_light, self.kwargs_unlensed_unmagnified_amp_ps, self.unlensed_image_model)
AttributeError: 'Imager' object has no attribute 'kwargs_unlensed_unmagnified_amp_ps'`

Setting it to None in the init does not solve the issue either because the Imager class in image_utils now always has an unlensed point source model (even if there is no lensed point source model). I was able to hack together a workaround by changing the Imager init to this:

> def __init__(self, components, lens_mass_model, src_light_model, lens_light_model=None, ps_model=None, kwargs_numerics={'supersampling_factor': 1}, min_magnification=0.0, for_cosmography=False):
> 
>         self.components = components
>         self.kwargs_numerics = kwargs_numerics
>         self.lens_mass_model = lens_mass_model
>         self.src_light_model = src_light_model
>         self.lens_light_model = lens_light_model
>         self.ps_model = ps_model
>         if ps_model is not None:
>             self.unlensed_ps_model = PointSource(point_source_type_list=['SOURCE_POSITION'], fixed_magnification_list=[False])
>         else:
>             self.unlensed_ps_model = None
>         self.lens_eq_solver = LensEquationSolver(self.lens_mass_model)
>         self.min_magnification = min_magnification
>         self.for_cosmography = for_cosmography
>         self.kwargs_unlensed_unmagnified_amp_ps=None
>         self.img_features = {} # Initialized to store metadata of images, will get updated for each lens

**Comment by jiwoncpark** [comment]
Sorry about that, fix pushed to master.
